---

- name: Set database defaults if not provided
  set_fact:
    merged_pulp_settings: "{{ pulp_settings_db_defaults|combine(pulp_settings, recursive=True) }}"

- block:
    - name: Create configuration directory for Pulp
      file:
        path: '{{ pulp_config_dir }}'
        state: directory
        owner: root
        group: '{{ pulp_group }}'
        mode: 0750

    - name: Create configuration file for Pulp
      template:
        src: settings.py.j2
        dest: '{{ pulp_settings_file }}'
        owner: root
        group: '{{ pulp_group }}'
        mode: 0640
        force: yes

  become: true
