---

- name: Fail when pulp_secret_key is not set
  assert:
    that: pulp_settings.secret_key is defined

- debug:
    var: pulp_install_plugins
    verbosity: 1
- debug:
    var: pulp_install_plugins_normalized_yml
    verbosity: 1
- debug:
    var: pulp_install_plugins_normalized
    verbosity: 1

- name: Load OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars'
  tags:
    - always

- name: Is this a supported version of CentOS
  fail:
    msg: Pulp Installer only supports CentOS 7.7 or higher.
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_version|float < 7.7

# Note: We cannot use `systemd-path search-binaries-default` because
# it wasn't added until systemd 239. Thus no CentOS 7 or Fedora 28
# support, etc.
- name: Enumerate default system PATH
  # pipefail is not needed due to grep's rc, but it resolves ansible-lint 306
  shell: |
    set -o pipefail
    systemctl show-environment | grep -E '^PATH=' | sed 's/PATH=//g'
  args:
    # Debian defaults to bourne, but it doesn't understand pipefail.
    executable: /bin/bash
  changed_when: false
  register: systemd_show_env_path
  check_mode: false

- name: set the default system PATH as a fact
  set_fact:
    default_bin_path: "{{ systemd_show_env_path.stdout }}"

- import_tasks: repos.yml
- import_tasks: install.yml

# This task is after install.yml since it gets installed then.
- name: Find and use the first found possible path to django-admin
  include_tasks: find_django_admin.yml
  with_items: "{{ pulp_django_admin_paths }}"
  when:
    # Works for both strings and lists to make sure not empty
    - pulp_django_admin_paths is not none
    - pulp_django_admin_paths | length > 0
    # Prevents running again once completed.
    - pulp_django_admin_path is not defined

- import_tasks: configure.yml
- import_tasks: wsgi.yml
