---
- block:

    - name: Install pulpcore-api service files
      template:
        src: pulpcore-api.service.j2
        dest: /lib/systemd/system/pulpcore-api.service
        owner: root
        group: root
        mode: 0644
      become: true
      notify: Restart pulpcore-api.service

  when: pulp_install_api_service |bool
