---
- name: Install several useful packages (distro-agnostic)
  package:
    name:
      - dstat
      - git
      - htop
      - iotop
      - jq
      - ncdu
      - tmux
      - tree
      - wget
      - curl
      - gnupg
      - rubygems
      - npm
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded

- name: Install several useful packages (CentOS 7 specific)
  package:
    name:
      - nc
      - python-virtualenvwrapper
      - ruby-devel
      - jnettop
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 7

- name: Install several useful packages (CentOS 8 specific)
  package:
    name:
      - bash-completion
      - dnf-utils
      - nc
      - python-django-bash-completion
      - python3-setuptools
      - python3-virtualenv-clone
      - vim-enhanced
      - ruby-devel
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 8

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 8

- name: Create virtualenvwrapper symlink
  file:
    src: "{{ pulp_install_dir }}/bin/virtualenvwrapper.sh"
    dest: /usr/bin/virtualenvwrapper.sh
    state: link
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 8

- name: Install several useful packages (Debian-specific)
  package:
    name:
      - bash-completion
      - fd-find
      - fzf
      - netcat
      - python3-setuptools
      - virtualenvwrapper
      - ripgrep
      - vim
      - software-properties-common
      - ruby-dev
      - jnettop
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when: ansible_facts.distribution == 'Debian'

- name: Install several useful packages (Fedora-specific)
  package:
    name:
      - bash-completion
      - dnf-utils
      - fd-find
      - fzf
      - nc
      - python-django-bash-completion
      - python3-setuptools
      - python3-virtualenvwrapper
      - ripgrep
      - vim-enhanced
      - ruby-devel
      - jnettop
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when: ansible_facts.distribution == 'Fedora'

- name: Install Minio Client
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin
    owner: '{{ developer_user }}'
    mode: 0750
...
